-- Supplement missing Nacos tables (idempotent)
CREATE TABLE IF NOT EXISTS his_config_info (
  id BIGINT NOT NULL,
  nid BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  data_id varchar(255) NOT NULL,
  group_id varchar(128) NOT NULL,
  app_name varchar(128) DEFAULT NULL,
  content TEXT NOT NULL,
  md5 varchar(32) DEFAULT NULL,
  gmt_create TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  gmt_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  src_user text,
  src_ip varchar(50) DEFAULT NULL,
  op_type char(10) DEFAULT NULL,
  tenant_id varchar(128) DEFAULT '',
  encrypted_data_key varchar(1024) NOT NULL DEFAULT '',
  publish_type varchar(50) DEFAULT 'formal',
  gray_name varchar(50) DEFAULT NULL,
  ext_info TEXT DEFAULT NULL,
  PRIMARY KEY (nid)
);
CREATE INDEX IF NOT EXISTS idx_gmt_create ON his_config_info (gmt_create);
CREATE INDEX IF NOT EXISTS idx_gmt_modified ON his_config_info (gmt_modified);
CREATE INDEX IF NOT EXISTS idx_did ON his_config_info (data_id);

CREATE TABLE IF NOT EXISTS roles (
  username varchar(50) NOT NULL,
  role varchar(50) NOT NULL,
  CONSTRAINT idx_user_role UNIQUE (username, role)
);

CREATE TABLE IF NOT EXISTS permissions (
  role varchar(50) NOT NULL,
  resource varchar(128) NOT NULL,
  action varchar(8) NOT NULL,
  CONSTRAINT uk_role_permission UNIQUE (role, resource, action)
);

INSERT INTO users (username, password, enabled)
VALUES ('nacos', '$2a$10$EuWPZHzz32dJN7jexM34MOeYirDdFAZm2kuWj7VEOJhhZkDrxfvUu', TRUE)
ON CONFLICT (username) DO NOTHING;

INSERT INTO roles (username, role) VALUES ('nacos', 'ROLE_ADMIN')
ON CONFLICT DO NOTHING;
