#!/usr/bin/env python3
"""Convert RuoYi MySQL SQL scripts to PostgreSQL."""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SQL_DIR = ROOT / "sql"
OUT_DIR = SQL_DIR / "postgresql"
PG_PASSWORD = "mm5621528"


def strip_mysql_noise(line: str) -> str:
    line = re.sub(r"`([^`]+)`", r"\1", line)
    line = re.sub(r"\s+comment\s+'[^']*'", "", line, flags=re.I)
    line = re.sub(r"\s+comment\s*=\s*'[^']*'", "", line, flags=re.I)
    line = re.sub(r"\)\s*engine\s*=\s*innodb[^;]*;", ");", line, flags=re.I)
    line = re.sub(r"\s+default\s+charset\s*=\s*\w+[^;,\n]*", "", line, flags=re.I)
    line = re.sub(r"\s+collate\s+\w+[^,)]*", "", line, flags=re.I)
    line = re.sub(r"\s+using\s+btree", "", line, flags=re.I)
    line = re.sub(r"\bauto_increment\s*=\s*\d+", "", line, flags=re.I)
    return line


def convert_types(line: str) -> str:
    line = re.sub(r"\bsysdate\s*\(\s*\)", "CURRENT_TIMESTAMP", line, flags=re.I)
    line = re.sub(r"\bdatetime\b", "TIMESTAMP", line, flags=re.I)
    line = re.sub(r"\blongtext\b", "TEXT", line, flags=re.I)
    line = re.sub(r"\blongblob\b", "TEXT", line, flags=re.I)
    line = re.sub(
        r"\bbigint\s*\(\s*20\s*\)\s+unsigned\s+not\s+null\s+auto_increment\b",
        "BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL",
        line,
        flags=re.I,
    )
    line = re.sub(
        r"\bbigint\s*\(\s*20\s*\)\s+not\s+null\s+auto_increment\b",
        "BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL",
        line,
        flags=re.I,
    )
    line = re.sub(
        r"\bint\s*\(\s*\d+\s*\)\s+not\s+null\s+auto_increment\b",
        "INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL",
        line,
        flags=re.I,
    )
    line = re.sub(r"\b(?:bigint|int)\s*\(\s*\d+\s*\)\s+unsigned\b", "BIGINT", line, flags=re.I)
    line = re.sub(r"\b(?:bigint|BIGINT|int|INTEGER)\s+unsigned\b", "BIGINT", line, flags=re.I)
    line = re.sub(r"\bint\s*\(\s*\d+\s*\)\s+unsigned", "INTEGER", line, flags=re.I)
    line = re.sub(r"\bINTEGER\s+unsigned\b", "INTEGER", line, flags=re.I)
    line = re.sub(r"\bbigint\s*\(\s*20\s*\)", "BIGINT", line, flags=re.I)
    line = re.sub(r"\bint\s*\(\s*\d+\s*\)", "INTEGER", line, flags=re.I)
    line = re.sub(r"\btinyint\s*\(\s*1\s*\)", "SMALLINT", line, flags=re.I)
    line = re.sub(r"\btinyint\b", "SMALLINT", line, flags=re.I)
    line = re.sub(r"\bauto_increment\b", "", line, flags=re.I)
    return line


def extract_indexes(create_block: str) -> tuple[str, list[str]]:
    indexes = []
    lines = []
    for line in create_block.splitlines():
        m = re.match(r",?\s*(?:key|index)\s+(\w+)\s*\(([^)]+)\)\s*,?\s*$", line.strip(), flags=re.I)
        if m:
            indexes.append((m.group(1), m.group(2)))
            continue
        m2 = re.match(r",?\s*unique\s+key\s+(\w+)\s*\(([^)]+)\)\s*,?\s*$", line.strip(), flags=re.I)
        if m2:
            indexes.append((m2.group(1), m2.group(2), True))
            continue
        lines.append(line)
    return "\n".join(lines), indexes


def convert_create_table(stmt: str) -> str:
    stmt = strip_mysql_noise(stmt)
    stmt = convert_types(stmt)
    body, indexes = extract_indexes(stmt)
    table_match = re.search(r"create\s+table\s+(\w+)", body, flags=re.I)
    table_name = table_match.group(1) if table_match else None
    body = re.sub(r",\s*\)", "\n)", body)
    if table_name and indexes:
        idx_sql = []
        for item in indexes:
            if len(item) == 3:
                idx_sql.append(
                    f"CREATE UNIQUE INDEX {item[0]} ON {table_name} ({item[1]});"
                )
            else:
                idx_sql.append(f"CREATE INDEX {item[0]} ON {table_name} ({item[1]});")
        body = body.rstrip().rstrip(";") + ";\n" + "\n".join(idx_sql)
    return body


def convert_sql_content(content: str) -> str:
    content = content.replace("\\'", "''")
    parts = re.split(r"(;[\r\n]+)", content)
    out = []
    buf = ""
    for part in parts:
        buf += part
        if not part.rstrip().endswith(";"):
            continue
        stmt = buf.strip()
        buf = ""
        if not stmt:
            continue
        upper = re.sub(r"/\*.*?\*/", "", stmt, flags=re.S)
        upper = re.sub(r"--[^\n]*", "", upper).strip().upper()
        if upper.startswith("SET NAMES") or "FOREIGN_KEY_CHECKS" in upper:
            continue
        if upper.startswith("USE "):
            continue
        if upper.startswith("CREATE TABLE") or upper.startswith("DROP TABLE"):
            if upper.startswith("CREATE TABLE"):
                out.append(convert_create_table(stmt))
            else:
                out.append(convert_types(strip_mysql_noise(stmt)))
        elif upper.startswith("INSERT"):
            out.append(convert_types(strip_mysql_noise(stmt)))
        else:
            out.append(convert_types(strip_mysql_noise(stmt)))
    return "\n\n".join(s for s in out if s.strip())


def patch_nacos_config(content: str) -> str:
    content = content.replace("com.mysql.cj.jdbc.Driver", "org.postgresql.Driver")
    content = content.replace(
        "jdbc:mysql://localhost:3306/ry-cloud?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8",
        "jdbc:postgresql://localhost:5432/ry_cloud",
    )
    content = content.replace("username: root", "username: postgres")
    content = content.replace("password: password", f"password: {PG_PASSWORD}")
    content = content.replace("validationQuery: SELECT 1 FROM DUAL", "validationQuery: SELECT 1")
    content = content.replace(
        "include: \\'*\\'\\n'",
        "include: \\'*\\'\\n\\n# PageHelper\\npagehelper:\\n  helperDialect: postgresql\\n  reasonable: true\\n  supportMethodsArguments: true\\n  params: count=countSql\\n'",
        1,
    )
    return content


def add_sequences() -> str:
    tables = [
        ("sys_dept", "dept_id"),
        ("sys_user", "user_id"),
        ("sys_post", "post_id"),
        ("sys_role", "role_id"),
        ("sys_menu", "menu_id"),
        ("sys_dict_type", "dict_id"),
        ("sys_dict_data", "dict_code"),
        ("sys_config", "config_id"),
        ("sys_notice", "notice_id"),
        ("sys_job", "job_id"),
        ("sys_job_log", "job_log_id"),
        ("sys_logininfor", "info_id"),
        ("sys_notice_read", "read_id"),
        ("gen_table", "table_id"),
        ("gen_table_column", "column_id"),
    ]
    lines = ["-- Reset identity sequences"]
    for table, col in tables:
        lines.append(
            f"SELECT setval(pg_get_serial_sequence('{table}', '{col}'), "
            f"COALESCE((SELECT MAX({col}) FROM {table}), 1));"
        )
    return "\n".join(lines)


def convert_ry_config(content: str) -> str:
    content = patch_nacos_config(content)
    content = re.sub(r"DROP DATABASE IF EXISTS.*?;\s*", "", content, flags=re.I)
    content = re.sub(r"CREATE DATABASE.*?;\s*", "", content, flags=re.I)
    content = content.replace("ry-config", "ry_config")
    content = content.replace("ry-cloud", "ry_cloud")
    return convert_sql_content(content)


def main():
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    ry_cloud_src = (SQL_DIR / "ry_20260417.sql").read_text(encoding="utf-8")
    ry_cloud_pg = convert_sql_content(ry_cloud_src) + "\n\n" + add_sequences()
    (OUT_DIR / "ry_cloud.sql").write_text(ry_cloud_pg, encoding="utf-8")

    ry_config_src = (SQL_DIR / "ry_config_20260611.sql").read_text(encoding="utf-8")
    (OUT_DIR / "ry_config.sql").write_text(convert_ry_config(ry_config_src), encoding="utf-8")

    init_sql = """-- Initialize PostgreSQL databases for RuoYi-Cloud
SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname IN ('ry_cloud', 'ry_config') AND pid <> pg_backend_pid();
DROP DATABASE IF EXISTS ry_cloud;
DROP DATABASE IF EXISTS ry_config;
CREATE DATABASE ry_cloud ENCODING 'UTF8';
CREATE DATABASE ry_config ENCODING 'UTF8';
"""
    (OUT_DIR / "init_databases.sql").write_text(init_sql, encoding="utf-8")
    print(f"Generated PostgreSQL scripts in {OUT_DIR}")


if __name__ == "__main__":
    main()
